version: '3'
services:
    # The FUI StoreConnect's Sensors API's server part
    storeconnect-sensors-api-server:
      image: storeconnect/sensors-api-server:latest
      container_name: storeconnect-sensors-api-server
      ports:
        - '8080:8080'
      volumes:
        - './conf/context.xml:/usr/local/tomcat/webapps/SensorThingsService/META-INF/context.xml'
      depends_on:
        - storeconnect-sensors-api-database

    # The FUI StoreConnect's Sensors API's database part
    storeconnect-sensors-api-database:
      image: storeconnect/sensors-api-postgis-database:latest
      container_name: storeconnect-sensors-api-database
      environment:
        - POSTGRES_DB=sensorthings
        - POSTGRES_USER=sensorthings
        - POSTGRES_PASSWORD=ChangeMe
      volumes:
        - './data/sensors-api-postgis-database:/var/lib/postgresql/data'
